import requests

if __name__ == '__main__':
    payload = {
        'vads_amount': '2000',
        'vads_ctx_mode': 'TEST',
        'vads_trans_id': '981035',
        'vads_trans_date': '20210908175230',
        'vads_trans_status': 'AUTHORISED',
        'vads_cust_email': 'test1@mail.fr',
        # 'vads_cust_email': 'sneelshneider@gmail.com',
        'vads_ext_info_Informations': '?contribution=4',
    }

    payload = {
        'vads_amount': '2000',
        'vads_auth_mode': 'FULL',
        'vads_auth_number': '3fc83b',
        'vads_auth_result': '00',
        'vads_capture_delay': '0',
        'vads_card_brand': 'CB',
        'vads_card_number': '466653XXXXXX0007',
        'vads_payment_certificate': 'd12d3dfad53005a6a6baf44cbfc0b1f53c6f2aed',
        'vads_ctx_mode': 'TEST',
        'vads_currency': '978',
        'vads_effective_amount': '2000',
        'vads_effective_currency': '978',
        'vads_site_id': '38529398',
        'vads_trans_date': '20210909175136',
        'vads_trans_id': '984931',
        'vads_trans_uuid': '6a3e96a9afa948958c11ca8c846f80a0',
        'vads_validation_mode': '0',
        'vads_version': 'V2',
        'vads_warranty_result': 'YES',
        'vads_payment_src': 'EC',
        'vads_cust_email': 'test1@mail.fr',
        'vads_tid': '001',
        'vads_sequence_number': '1',
        'vads_acquirer_network': 'CB',
        'vads_contract_used': '5254450',
        'vads_trans_status': 'AUTHORISED',
        'vads_expiry_month': '6',
        'vads_expiry_year': '2022',
        'vads_bank_code': '17807',
        'vads_bank_label': 'Banque Populaire Occitane',
        'vads_bank_product': '5',
        'vads_pays_ip': 'FR',
        'vads_presentation_date': '20210909175136',
        'vads_effective_creation_date': '20210909175136',
        'vads_occurrence_type': 'UNITAIRE',
        'vads_operation_type': 'DEBIT',
        'vads_result': '00',
        'vads_extra_result': '',
        'vads_card_country': 'FR',
        'vads_language': 'en',
        'vads_brand_management': '{"userChoice":false,"brandList":"CB|VPAY","brand":"CB"}',
        'vads_hash': '5d5bb1ed3f3c7b42f5727fc9cab8616c16e19985115229cb6e1a7dca7f62203e',
        'vads_url_check_src': 'PAY',
        'vads_action_mode': 'INTERACTIVE',
        'vads_payment_config': 'SINGLE',
        'vads_page_action': 'PAYMENT',
        'vads_ext_info_Informations': '?contribution=4',
        'vads_threeds_enrolled': 'Y',
        'vads_threeds_auth_type': 'CHALLENGE',
        'vads_threeds_eci': '05',
        'vads_threeds_xid': 'Qm5ZQ1NRamNNSG5keFkwcGZ3bTY=',
        'vads_threeds_cavvAlgorithm': '2',
        'vads_threeds_status': 'Y',
        'vads_threeds_sign_valid': '1',
        'vads_threeds_error_code': '',
        'vads_threeds_exit_status': '10',
        'vads_threeds_cavv': 'Q**************************=',
        'signature': 'OHgHewZAeVkUmbceEuR2m4/4THRzgKRR/iLZI+v/QOE='
    }

    r = requests.post('http://192.168.1.27:8001/api/vads/ipn/', data=payload)
    
    print (r.status_code)
    print (r.json())