# Generated by Django 2.2.19 on 2021-07-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_auto_20210528_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='google',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
