# Generated by Django 2.2.19 on 2021-07-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('widgets', '0003_auto_20210706_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='SchoolWidget',
        ),
    ]
