# Generated by Django 2.2.19 on 2021-08-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_auto_20210726_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placegalleryimage',
            name='place',
        ),
    ]
