# Generated by Django 2.2.19 on 2021-08-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_remove_placegalleryimage_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceGalleryImage',
        ),
    ]
