# Generated by Django 2.2.19 on 2021-08-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_delete_placegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='maps',
            field=models.URLField(blank=True, default='', verbose_name='URL Google Maps'),
        ),
    ]
