# Generated by Django 3.2.7 on 2021-11-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0007_place_maps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Contact: Lieu'},
        ),
    ]
