# Generated by Django 2.2.19 on 2021-07-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profilepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepage',
            options={'verbose_name': 'Profile: Main Page'},
        ),
    ]
