# Generated by Django 2.2.19 on 2021-07-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('user', '0005_auto_20210721_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePage',
        ),
    ]
