# Generated by Django 3.2.7 on 2021-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210803_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
