# Generated by Django 3.2.7 on 2021-09-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('user', '0009_auto_20210924_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Auth: Connexion',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Est administrateur ?'),
        ),
    ]
