# Generated by Django 2.2.19 on 2021-05-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Demo: Index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DemoPage1',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template', models.CharField(default='demo/demo_page.html', max_length=125)),
            ],
            options={
                'verbose_name': 'Demo: Page Demo 1',
            },
            bases=('wagtailcore.page',),
        ),
    ]
