# Generated by Django 2.2.19 on 2021-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='template',
            field=models.CharField(default='demo/demo_page.html', max_length=125),
        ),
    ]
