# Generated by Django 2.2.19 on 2021-05-27 19:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('contact', '0001_initial'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_place', to='widgets.Place', verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='agency',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='acmformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='contact.ACMContactPage'),
        ),
    ]
