# Generated by Django 2.2.19 on 2021-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contact', '0002_auto_20210527_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='who_arewe',
            name='agencies',
        ),
        migrations.RemoveField(
            model_name='who_arewe',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='seo_description',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' description. This will appear in head metadata.", max_length=255, verbose_name='page description'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' keywords. This will appear in head metadata.", max_length=255, verbose_name='page keywords'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='ContactIndexPage',
        ),
        migrations.DeleteModel(
            name='Who_AreWe',
        ),
    ]
