# Generated by Django 2.2.19 on 2021-07-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210528_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_places', to='widgets.Place', verbose_name='Lieu'),
        ),
    ]
