# Generated by Django 2.2.19 on 2021-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='web',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
