# Generated by Django 2.2.19 on 2021-07-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20210727_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='fiche_onisep',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='web',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
