# Generated by Django 2.2.19 on 2021-08-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20210727_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='type_contrat_prive',
            field=models.CharField(blank=True, choices=[('DEFAUT', 'DEFAUT'), ('AUTRE', 'AUTRE'), ('SANS OBJET', 'SANS_OBJET'), ('HORS CONTRAT', 'HORS_CONTRAT'), ("CONTRAT D'ASSOCIATION TOUTES CLASSES", 'CONTRAT_ASSO_TTS_CLASSES'), ('CONTRAT ASSOCIATION PARTIE DES CLASSES', 'CONTRAT_ASSO_PART_CLASSES'), ('CONTRAT SIMPLE TOUTES CLASSES', 'CONTRAT_SIMPLE_TTS_CLASSES'), ('CONTRAT SIMPLE POUR PARTIE DES CLASSES', 'CONTRAT_SIMPLE_PART_CLASSES')], default='DEFAUT', max_length=64, null=True),
        ),
    ]
