# Generated by Django 3.2.7 on 2021-10-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20210803_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Education: Ecole'},
        ),
    ]
