# Generated by Django 2.2.19 on 2021-07-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('memberships', '0003_auto_20210707_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationPage',
        ),
    ]
