# Generated by Django 2.2.19 on 2021-07-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_member_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpage',
            name='template_landing',
            field=models.CharField(default='memberships/landing_page.html', max_length=125),
        ),
    ]
