# Generated by Django 2.2.19 on 2021-07-17 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('memberships', '0007_registrationpage_template_landing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationPage',
            new_name='RegistrationPage2',
        ),
        migrations.AlterField(
            model_name='member',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ligne 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, default='Martinique', max_length=60, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_home',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Téléphone fixe'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_pro',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Téléphone professionnel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Code Postal'),
        ),
    ]
