# Generated by Django 2.2.19 on 2021-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_auto_20210717_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationpage',
            name='template_credentials',
        ),
        migrations.RemoveField(
            model_name='registrationpage',
            name='template_landing',
        ),
        migrations.RemoveField(
            model_name='registrationpage',
            name='template_memberships',
        ),
        migrations.AddField(
            model_name='registrationpage',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='registrationpage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='registrationpage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address'),
        ),
    ]
