# Generated by Django 2.2.19 on 2021-07-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_auto_20210719_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='registrationpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='registrationpage',
            name='to_address',
        ),
    ]
