# Generated by Django 2.2.19 on 2021-07-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0011_auto_20210719_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.AddField(
            model_name='member',
            name='newsletter_sub',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Abonné newsletter'),
        ),
    ]
