# Generated by Django 2.2.19 on 2021-07-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('memberships', '0016_auto_20210721_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChildrenPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Profile: Children Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='member',
            name='newsletter_sub',
            field=models.BooleanField(default=True, verbose_name='Abonné newsletter'),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.CharField(default='', max_length=60, verbose_name='Code Postal'),
        ),
    ]
