# Generated by Django 2.2.19 on 2021-07-22 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('memberships', '0017_auto_20210722_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileChildrenPage',
            new_name='ProfileChildrenIndexPage',
        ),
    ]
