# Generated by Django 2.2.19 on 2021-07-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0019_profilechildrenpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilechildrenindexpage',
            options={'verbose_name': 'Profile: Children Index Page'},
        ),
        migrations.AddField(
            model_name='memberchild',
            name='dob',
            field=models.DateField(default=None, verbose_name='Date de naissance'),
            preserve_default=False,
        ),
    ]
