# Generated by Django 2.2.19 on 2021-07-26 17:40

from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0020_auto_20210722_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberchild',
            name='foo',
            field=models.BooleanField(default=True),
        ),
        # migrations.AlterField(
        #     model_name='memberchild',
        #     name='grade',
        #     field=models.CharField(blank=True, choices=[('Défaut', 'DEFAUT'), ('AUTRE', 'OTHER'), ('Très Petite Section', 'TPS'), ('Petite Section', 'PS'), ('Moyenne Section', 'MS'), ('Grande Section', 'GS'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6eme', 'C6'), ('5eme', 'C5'), ('4eme', 'C4'), ('3eme', 'C3'), ('2nd', 'L2'), ('1ere', 'L1'), ('Terminale', 'TERM'), ('Etudes', 'UNI')], default=education.models.GradeEnum('Défaut'), max_length=20, null=True, verbose_name='Classe'),
        # ),
        # migrations.AlterField(
        #     model_name='memberchild',
        #     name='school',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='education.School'),
        # ),
    ]
