# Generated by Django 2.2.19 on 2021-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0022_auto_20210726_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberchild',
            name='bar',
            field=models.BooleanField(default=True),
        ),
    ]
