# Generated by Django 2.2.19 on 2021-07-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0023_memberchild_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberchild',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='memberchild',
            name='school',
        ),
    ]
