# Generated by Django 2.2.19 on 2021-07-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0025_auto_20210726_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberchild',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='memberchild',
            name='foo',
        ),
    ]
