# Generated by Django 2.2.19 on 2021-08-03 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import education.models
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('memberships', '0026_auto_20210726_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateField(verbose_name='Date fin')),
                ('date_start', models.DateField(verbose_name='Date début')),
                ('is_active', models.BooleanField(default=False, verbose_name='Est actif ?')),
                ('is_payable', models.BooleanField(default=False, verbose_name="Disponible à l'achat ?")),
            ],
        ),
        migrations.CreateModel(
            name='ContributionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Nom tarif')),
                ('price', models.FloatField(default=0.0, verbose_name='Prix')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileContribution',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Profil: Cotisations',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='memberchild',
            name='grade',
            field=models.CharField(blank=True, default=education.models.GradeEnum('Défaut'), max_length=20, null=True, verbose_name='Classe'),
        ),
        migrations.CreateModel(
            name='MemberContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Prix achat')),
                ('date_bought', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date achat')),
                ('contribution_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_plan', to='memberships.ContributionPlan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='memberships.Member')),
            ],
        ),
    ]
