# Generated by Django 2.2.19 on 2021-08-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('memberships', '0027_auto_20210803_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Intitulé'),
        ),
        migrations.AddField(
            model_name='contributionplan',
            name='contribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='memberships.Contribution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributionplan',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Intitulé'),
        ),
    ]
