# Generated by Django 2.2.19 on 2021-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0029_auto_20210810_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': 'Cotisation'},
        ),
        migrations.AlterModelOptions(
            name='contributionplan',
            options={'verbose_name': 'Cotisation Tarif'},
        ),
        migrations.AddField(
            model_name='contributionplan',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
