# Generated by Django 2.2.19 on 2021-08-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0030_auto_20210810_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercontribution',
            name='contribution_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='memberships.ContributionPlan'),
        ),
    ]
