# Generated by Django 2.2.19 on 2021-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0031_auto_20210812_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionplan',
            name='price',
        ),
        migrations.AddField(
            model_name='contribution',
            name='base_price',
            field=models.FloatField(default=0.0, verbose_name='Prix de base'),
        ),
        migrations.AddField(
            model_name='contributionplan',
            name='mod',
            field=models.FloatField(default=0.0, verbose_name='Modificateur de prix'),
        ),
    ]
