# Generated by Django 2.2.19 on 2021-08-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0032_auto_20210812_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercontribution',
            name='contribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='memberships.Contribution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membercontribution',
            name='contribution_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_members', to='memberships.ContributionPlan'),
        ),
    ]
