# Generated by Django 2.2.19 on 2021-08-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0034_remove_membercontribution_contribution_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membre'},
        ),
        migrations.AlterModelOptions(
            name='memberchild',
            options={'verbose_name': 'Membre: Enfant'},
        ),
        migrations.AlterModelOptions(
            name='membercontribution',
            options={'verbose_name': 'Membre: Cotisation'},
        ),
    ]
