# Generated by Django 2.2.19 on 2021-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0035_auto_20210829_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercontribution',
            name='transaction_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID transaction'),
        ),
    ]
