# Generated by Django 2.2.19 on 2021-09-10 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0037_auto_20210909_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Intitulé')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('condition', wagtail.core.fields.RichTextField(blank=True)),
                ('date_end', models.DateField(verbose_name='Date fin')),
                ('date_start', models.DateField(verbose_name='Date début')),
                ('is_active', models.BooleanField(default=False, verbose_name='Est actif ?')),
            ],
            options={
                'verbose_name': 'Candidature',
                'ordering': ['-date_end'],
            },
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date accord')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_app', to='memberships.Application')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='memberships.Member')),
            ],
            options={
                'verbose_name': 'Membre: Candidature',
            },
        ),
    ]
