# Generated by Django 2.2.19 on 2021-09-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0038_application_memberapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-is_active', '-date_end'], 'verbose_name': 'Candidature'},
        ),
    ]
