# Generated by Django 2.2.19 on 2021-09-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0040_auto_20210914_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplicationchild',
            name='member_application',
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_app', to='memberships.Application', verbose_name='Candidature'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='memberships.Member', verbose_name='Membre'),
        ),
        migrations.CreateModel(
            name='MemberApplicationOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('member_application_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.MemberApplicationChild')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
