# Generated by Django 2.2.19 on 2021-09-14 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0043_auto_20210914_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplicationchild',
            name='application',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='school_lists', to='memberships.MemberApplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplicationchild',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='memberapplicationchild',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date signature'),
        ),
        migrations.DeleteModel(
            name='MemberApplicationOrderable',
        ),
    ]
