# Generated by Django 2.2.19 on 2021-09-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0045_auto_20210914_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberapplicationchild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_application', to='memberships.MemberChild', verbose_name='Enfant'),
        ),
    ]
