# Generated by Django 3.2.7 on 2021-09-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0046_auto_20210914_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='child',
            field=models.ForeignKey(default=None, limit_choices_to={'member': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='memberships.member', verbose_name='Membre')}, on_delete=django.db.models.deletion.CASCADE, related_name='child_application', to='memberships.memberchild', verbose_name='Enfant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberapplicationchild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_child_application', to='memberships.memberchild', verbose_name='Enfant'),
        ),
    ]
