# Generated by Django 3.2.7 on 2021-09-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0047_auto_20210915_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberapplication',
            options={'ordering': ['member', 'application', 'child'], 'verbose_name': 'Membre: Candidature'},
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_application', to='memberships.memberchild', verbose_name='Enfant'),
        ),
    ]
