# Generated by Django 3.2.7 on 2021-09-16 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0048_auto_20210915_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberapplication',
            options={'ordering': ['member', 'application', 'child'], 'verbose_name': 'Membre: Candidature - Gérez les candidatures parents', 'verbose_name_plural': 'Membre: Candidature - Gérez les candidatures parents'},
        ),
        migrations.AlterModelOptions(
            name='membercontribution',
            options={'verbose_name': 'Membre: Cotisation - Gérez les cotisations parents', 'verbose_name_plural': 'Membre: Cotisation - Gérez les cotisations parents'},
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='date_signed',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date signature'),
        ),
    ]
