# Generated by Django 3.2.7 on 2021-09-17 21:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('memberships', '0049_auto_20210915_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileApplicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Profile: Candidatures Parent',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterModelOptions(
            name='profileaccountpage',
            options={'verbose_name': 'Profile: Compte Parent'},
        ),
    ]
