# Generated by Django 3.2.7 on 2021-09-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0053_profiledocumentspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profiledocumentspage',
            options={'verbose_name': 'Profil: Documents'},
        ),
    ]
