# Generated by Django 3.2.7 on 2021-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0055_membercontribution_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercontribution',
            name='method',
            field=models.CharField(choices=[('ON', 'En ligne'), ('SO', 'Espèce'), ('JR', 'Chèque'), ('SR', 'Crédit')], default='ON', max_length=2),
        ),
    ]
