# Generated by Django 3.2.7 on 2021-09-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0056_alter_membercontribution_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercontribution',
            options={'ordering': ['-date_bought'], 'verbose_name': 'Membre: Cotisation - Gérez les cotisations parents', 'verbose_name_plural': 'Membre: Cotisation - Gérez les cotisations parents'},
        ),
    ]
