# Generated by Django 3.2.7 on 2021-10-02 16:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('memberships', '0058_profileschoollist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMembers',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membres: Parents'},
        ),
        migrations.AlterField(
            model_name='member',
            name='job',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Profession'),
        ),
    ]
