# Generated by Django 3.2.7 on 2021-10-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0060_auto_20211004_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercontribution',
            options={'ordering': ['contribution__is_active', '-date_bought'], 'verbose_name': 'Membre: Cotisation - Gérez les cotisations parents', 'verbose_name_plural': 'Membre: Cotisation - Gérez les cotisations parents'},
        ),
    ]
