# Generated by Django 3.2.7 on 2021-10-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0061_alter_membercontribution_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberchild',
            options={'ordering': ['id'], 'verbose_name': 'Membre: Enfant'},
        ),
        migrations.AlterModelOptions(
            name='membercontribution',
            options={'ordering': ['-contribution__is_active', '-date_bought'], 'verbose_name': 'Membre: Cotisation - Gérez les cotisations parents', 'verbose_name_plural': 'Membre: Cotisation - Gérez les cotisations parents'},
        ),
    ]
