# Generated by Django 3.2.7 on 2021-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0063_alter_memberchild_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercontribution',
            name='method',
            field=models.CharField(choices=[('ON', 'En ligne'), ('CASH', 'Espèce'), ('CHCK', 'Chèque'), ('CRED', 'Crédit'), ('VRMT', 'Virement'), ('AUTR', 'Autre')], default='ON', max_length=10),
        ),
    ]
