# Generated by Django 3.2.7 on 2021-11-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0064_alter_membercontribution_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-is_active', '-date_end'], 'verbose_name': 'Candidature - Créer des candidatures'},
        ),
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-date_end'], 'verbose_name': 'Cotisation - Créer des cotisations'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membre: Parent'},
        ),
    ]
