# Generated by Django 2.2.19 on 2021-05-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210527_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blankindexpage',
            options={'verbose_name': 'Template: Index'},
        ),
        migrations.AlterModelOptions(
            name='freehtmlpage',
            options={'verbose_name': 'Template: Page'},
        ),
    ]
