# Generated by Django 3.2.7 on 2021-09-27 16:31

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_testseopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoarewepage',
            name='history',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Historique'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='quote',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Citation'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='quote_author',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Auteur citation'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='tile_admin_council',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Conseil d'adminstration"),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='tile_cen',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Conseil éducation nationale'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='tile_class_council',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Conseil de classe'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='tile_disci_council',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Conseil de discipline'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='tile_education',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Comité éducation santé citoyenneté'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='tile_languages',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Commission des langues régionales'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='tile_scholarships',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Commission des bourses'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='tile_schoo_council',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Conseil d'école"),
        ),
    ]
