# Generated by Django 3.2.7 on 2021-11-12 15:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211112_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoAreWeTileMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(default='', max_length=128, verbose_name='Icon')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Titre')),
                ('text', models.CharField(default='', max_length=255, verbose_name='Contenu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhoAreWeTileSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(default='', max_length=128, verbose_name='Icon')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Titre')),
                ('text', models.CharField(default='', max_length=255, verbose_name='Contenu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='whoarewepage',
            name='tile_main',
        ),
        migrations.RemoveField(
            model_name='whoarewepage',
            name='tile_sub',
        ),
        migrations.DeleteModel(
            name='WhoAreWePageTile',
        ),
        migrations.AddField(
            model_name='whoarewetilesub',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles_sub', to='home.whoarewepage'),
        ),
        migrations.AddField(
            model_name='whoarewetilemain',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles_main', to='home.whoarewepage'),
        ),
    ]
