# Generated by Django 3.2.7 on 2021-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211112_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoarewetilesub',
            name='icon',
            field=models.CharField(default='', help_text='Liste: https://semantic-ui.com/elements/icon.html', max_length=128, verbose_name='Icon classe'),
        ),
    ]
