# Generated by Django 3.2.7 on 2021-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_whoarewetilesub_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoarewetilesub',
            name='icon',
            field=models.CharField(default='', help_text='<a target="_blank" href="https://semantic-ui.com/elements/icon.html">Liste</a>', max_length=128, verbose_name='Icon classe'),
        ),
    ]
