# Generated by Django 2.2.19 on 2021-09-07 14:39

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionvads',
            name='order_status',
        ),
        migrations.AddField(
            model_name='transactionvads',
            name='status',
            field=models.IntegerField(choices=[(0, 'WAITING'), (1, 'UNKNOW_TRANSACTION'), (2, 'TEST_TRANSACTION'), (10, 'INCORRECT_PAYLOAD'), (11, 'INCORRECT_AMOUNT'), (12, 'INCORRECT_PRODUCT'), (20, 'COMPLETED')], default=payment.models.OrderStatusEnum(0)),
        ),
    ]
