# Generated by Django 2.2.19 on 2021-09-07 21:07

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210907_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionvads',
            name='status',
            field=models.IntegerField(choices=[(0, 'WAITING'), (1, 'UNKNOW_TRANSACTION'), (2, 'TEST_TRANSACTION'), (3, 'PARSE_FAILED'), (4, 'INCORRECT_INFORMATIONS'), (10, 'INCORRECT_PAYLOAD'), (11, 'INCORRECT_AMOUNT'), (12, 'INCORRECT_PRODUCT'), (13, 'INCORRECT_CUSTOMER'), (20, 'COMPLETED')], default=payment.models.OrderStatusEnum(0)),
        ),
    ]
