# Generated by Django 2.2.19 on 2021-09-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210907_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionvads',
            name='cust_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='transactionvads',
            name='ext_info_1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transactionvads',
            name='trans_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionvads',
            name='trans_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
