# Generated by Django 2.2.19 on 2021-09-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210908_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionvads',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
