# Generated by Django 3.2.7 on 2021-10-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210908_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionvads',
            options={'verbose_name': 'Paiement: Transactions VADS'},
        ),
    ]
