# Generated by Django 3.2.7 on 2021-11-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_transactionvads_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionvads',
            options={'verbose_name': 'Paiement: Transactions VADS', 'verbose_name_plural': 'Paiement: Transactions VADS'},
        ),
    ]
